import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.dirname(fileURLToPath(import.meta.url));
console.log("PAPER_DRIVER=v49");
console.log("PAPER_DRIVER_DELEGATES_TO=verify_integrity_v49.mjs");
const result = spawnSync(process.execPath, ["verify_integrity_v49.mjs"], { cwd: root, stdio: "inherit", shell: false, env: process.env });
if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status ?? 1);
console.log("PAPER_V49_CLAIMS=PASS");
